---
- name: Install Fail2Ban
  apt:
    name: fail2ban
    state: present
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Install jail.local from template
  template:
    src: jail.local.j2
    dest: /etc/fail2ban/jail.local
    owner: root
    group: root
    mode: '0644'
  notify: Restart Fail2Ban