---
- name: Print the hostname
  ansible.builtin.debug:
    msg: "The hostname is {{ ansible_hostname }}"

- name: Get the latest node_exporter version
  ansible.builtin.shell: |
    set -euo pipefail
    curl -s https://api.github.com/repos/prometheus/node_exporter/releases/latest |
    grep 'tag_name' | cut -d '"' -f 4
  register: latest_version
  changed_when: false

- name: Download node_exporter
  ansible.builtin.get_url:
    url: >
      https://github.com/prometheus/node_exporter/releases/download/{{ latest_version.stdout }}/
      node_exporter-{{ latest_version.stdout | replace('v', '') }}.linux-amd64.tar.gz
    dest: /tmp/node_exporter.tar.gz
    mode: '0644'
    owner: root
    group: root

- name: Extract node_exporter
  ansible.builtin.unarchive:
    src: /tmp/node_exporter.tar.gz
    dest: /tmp/
    remote_src: true
    creates: /tmp/node_exporter-{{ latest_version.stdout | replace('v', '') }}.linux-amd64

- name: Move binary
  ansible.builtin.copy:
    src: /tmp/node_exporter-{{ latest_version.stdout | replace('v', '') }}.linux-amd64/node_exporter
    dest: /usr/local/bin/node_exporter
    mode: '0755'
    remote_src: true

- name: Create nodeuser
  ansible.builtin.user:
    name: nodeuser
    shell: /bin/false
    create_home: false
    state: present

- name: Create systemd service
  ansible.builtin.template:
    src: node_exporter.service.j2
    dest: /etc/systemd/system/node_exporter.service
    owner: root
    group: root
    mode: '0644'
  notify: Reload systemd

- name: Set permissions
  ansible.builtin.file:
    path: "{{ item }}"
    owner: nodeuser
    group: nodeuser
    recurse: true
  loop:
    - /etc/node_exporter

- name: Set ownership of binary
  ansible.builtin.file:
    path: /usr/local/bin/node_exporter
    owner: nodeuser
    group: nodeuser
    state: file

- name: Enable and start node_exporter
  ansible.builtin.systemd:
    name: node_exporter
    enabled: true
    state: started

- name: Add job to prometheus.yml
  ansible.builtin.lineinfile:
    path: "{{ prometheus_conf_paths }}"
    line: "{{ lookup('template', 'prometheus_job.j2') }}"
  delegate_to: "{{ prometheus_host }}"

- name: Stop Prometheus (docker)
  community.docker.docker_container:
    name: prometheus
    state: stopped
  delegate_to: "{{ prometheus_host }}"
  when:
    - setup_prometheus | default(false)

- name: Start Prometheus (docker)
  community.docker.docker_container:
    name: prometheus
    state: started
  delegate_to: "{{ prometheus_host }}"
  when:
    - setup_prometheus | default(false)
