---
- name: Import Fail2Ban installation tasks
  ansible.builtin.import_tasks: install_fail2ban.yml
  when:
    - install_fail2ban | default(false)

- name: Import Node Exporter installation tasks
  ansible.builtin.import_tasks: install_nodeexporter.yml
  when:
    - install_nodeexporter | default(false)

- name: Import UFW installation tasks
  ansible.builtin.import_tasks: install_ufw.yml
  when:
    - install_ufw | default(false)

- name: Import Docker installation tasks
  ansible.builtin.import_tasks: install_docker.yml
  when:
    - install_docker | default(false)

- name: Import base VMESS configuration tasks
  ansible.builtin.import_tasks: install_base_vmess.yml
  when:
    - server_name is defined
    - server_name | length > 0
